config/routes.rb
Rails.application.routes.draw do  

  devise_for :log_users
  authenticated :log_user do
    root to: 'companies#index'
  end
  root to: 'tops#index'

  resources :companies do
    resources :comments do
    end
    resources :groups do
      resources :users do
        resources :name_cards
      end
    end
  end
  
  resources :tops, only: [:index]

  post "companies/comment" => "companies#comment"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :company
 # belongs_to :user
 # belongs_to :group
 # belongs_to :name_card
end

app/models/comment_group.rb
class CommentGroup < ApplicationRecord
  belongs_to :group
end

app/models/comment_user.rb
class CommentUser < ApplicationRecord
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :groups
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
  validates :address, presence: true, length: {maximum: 100}
  validates :url, length: {maximum: 100}, format: URI.regexp(['http','https']), allow_blank: true
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}, allow_blank: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :company
  has_many :users
  has_many :comment_groups, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
end

app/models/log_user.rb
class LogUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #validates :name, presence: true, length: { maximum: 30 }

  has_many :companies
end

app/models/name_card.rb
class NameCard < ApplicationRecord
  belongs_to :user
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
 # validates :address, length: {maximum: 100}, presence: true
 # validates :url, length: {maximum: 100, allow: nil}, format: URI.regexp(['http', 'https']), allow_nil: true
 # validates :tel, :fax, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}

  mount_uploader :image, ImageUploader

end

app/models/post.rb
class Post < ApplicationRecord
  def search
    if search
      Post.where(['content LIKE ?', "%#{search}"])
    else
      Post.all
    end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :group
  has_many :name_cards
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}
  validates :mail, length: { maximum: 100, minimun: 3 }, allow_blank: true, uniqueness: true, format: { with: /\A[A-Z0-9\.\_\-_+]+@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
end

app/controllers/name_cards_controller.rb
class NameCardsController < ApplicationController
  before_action :set_company, :set_group, :set_user
  before_action :set_name_card, only: [:show, :edit, :update, :destroy]

  def index
    @name_cards= @user.name_cards.page(params[:page]).per(6)
  end

  def show
  end

  def new
    @name_card = @user.name_cards.new
  end

  def create
    @name_card = @user.name_cards.new(name_card_params)

    if @name_card.save
      redirect_to [@company, @group, @user, @name_card], notice: 'NameCard was succeessfully created'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @name_card.update(name_card_params)
      redirect_to [@company, @group, @user, @name_card], notice: 'NameCard was successfully updated'
    else
      render action: 'edit'
    end
  end

  def destroy
    @name_card.destroy
    redirect_to company_group_user_name_cards_path
  end

  private


  def set_name_card
    @name_card = @user.name_cards.find(params[:id])
  end

  def name_card_params
    params.require(:name_card).permit(:name, :address, :fax, :tel, :url, :image, :image_cache)
  end

  def set_company
      id = params[:company_id] ? params[:company_id] : params[:id]
      @company = Company.find(id)
    end
    
    def set_group
      group_id = params[:group_id] ? params[:group_id] : params[:id]
      @group = @company.groups.find(group_id)
    end
    
    def set_user
      user_id = params[:user_id] ? params[:user_id] : params[:id]
      @user = @group.users.find(user_id)
    end




end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def search
    @posts = Post.search(params[:search])
  end

  def index
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :authenticate_log_user!
    
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_company, :set_group
before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = @group.users.page(params[:page]).per(6)
  end

  def show
  end

  def new
    @user = @group.users.new
  end

  def create
    @user = @group.users.new(user_params)

    if @user.save
      redirect_to [@company, @group, @user], notice: '部署を追加しました.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to [@company, @group, @user], notice: '追加しました'
    end
  end

  def destroy
    @user.destroy
    redirect_to company_group_users_path(@company, @group)
  end

  private

  def user_params
    params.require(:user).permit(:name, :mail, :tel, :comment)
  end

  def set_company
      id = params[:company_id] ? params[:company_id] : params[:id]
      @company = Company.find(id)
  end
    
  def set_group
      group_id = params[:group_id] ? params[:group_id] : params[:id]
      @group = @company.groups.find(group_id)
  end
    
  def set_user
      user_id = params[:user_id] ? params[:user_id] : params[:id]
      @user = @group.users.find(user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/log_users_helper.rb
module LogUsersHelper

end

app/helpers/name_cards_helper.rb
module NameCardsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/name_cards/_form.html.erb
<div class="container">
   <div class="content-center">
     <%= form_for([@company, @group, @user, @name_card]) do |f| %>
       <% if @name_card.errors.any? %>
       <div id="error_exp;anation">
         <h2><%= pluralize(@name_card.errors.count, 'エラー') %>saved</h2>

         <ul>
           <% @name_card.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
         </ul>
       </div>
     <% end %>

     <div class="field">
       <div class="form-low">
         <div class="col-md-6 col-xs-12">
          <%= f.text_field :name, autofocus: true, placeholder: "名前", class: "form-control" %><br>
          <%= f.text_field :address, autofocus: true, placeholder: "住所", class: "form-control" %><br>
          <%= f.text_field :tel, autofocus: true, placeholder: "電話番号", class: "form-control" %><br>
	 </div>
	 <div class="col-md-6 col-xs-12">
          <%= f.text_field :fax, autofocus: true, placeholder: "ファックス", class: "form-control" %><br>
          <%= f.text_field :url, autofocus: true, placeholder: "Webサイト", class: "form-control" %><br>
         </div>
       <div class="field">
         <%= f.label :名刺 %>
         <%= f.file_field :image %>
       </div><br>


     </div>
     </div>
     <div class="actions text-center "><br>
        <%= f.submit "更新する", class:'btn btn-primary'%>
     </div>
   <% end %>
   </div>
 </div>

app/views/name_cards/edit.html.erb
<div class="text-center"><h2>名刺編集</h2></div>
<br>

<%= render 'form' %>

<%= link_to '詳細画面に戻る', company_group_user_name_card_path(@company, @group, @user, @name_card), class:'btn btn-primary' %> 
<%= link_to '名刺一覧に戻る', company_group_user_name_cards_path, class:'btn btn-primary' %>

app/views/name_cards/index.html.erb
<div class="text-primary"><h4><%= @company.name %>:<%= @group.name %>:<%= @user.name %>さん</h4>
<h3>名刺情報</h3></div><br>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>氏名</th>
      <th>住所</th>
      <th>電話番号</th>
      <th>ファックス</th>
      <th>Webサイト</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
     <% @name_cards.each do |name_card| %>
       <tr>
         <td><%= name_card.name %></td>
         <td><%= name_card.address %></td>
         <td><%= name_card.tel %></td>
         <td><%= name_card.fax %></td>
         <td><%= name_card.url %></td>
         <td>
           <%= link_to '詳細', company_group_user_name_card_path(@company, @group, @user, name_card),class:'btn btn-default' %>
           <%= link_to '編集', edit_company_group_user_name_card_path(@company, @group, @user, name_card),class:'btn btn-default' %>
           <%= link_to '削除', company_group_user_name_card_path(@company, @group, @user, name_card), method: :delete, data: { confirm: '削除しますか?' }, class:'btn btn-default' %>
       </td>
       </tr>
     <% end %>
  </tbody>
</table>

<%= paginate @name_cards %>

<br>

<div class="text-center">
<%= link_to '名刺を追加する', new_company_group_user_name_card_path,class:'btn btn-primary' %>
<%= link_to '社員一覧へ戻る', company_group_users_path,class:'btn btn-primary' %>
</div>

app/views/name_cards/new.html.erb
<div class="text-center">
  <h2>名刺登録</h2>
</div>
<br>
<%= render 'form' %>
<%= link_to '名刺一覧へ戻る', company_group_user_name_cards_path, class:'btn btn-primary' %>

app/views/name_cards/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-hover">
   <thead>
     <th>名前</th>
     <th>住所</th>
     <th>電話番号</th>
     <th>ファックス</th>
     <th>Webサイト</th>
   </thead>
 
   <tbody>
     <tr>
       <td><%= @name_card.name %></td>
       <td><%= @name_card.address %></td>
       <td><%= @name_card.tel %></td>
       <td><%= @name_card.fax %></td>
       <td><%= @name_card.url %></td>
     </tr>
   </tbody>
 </table>
  
  <div class="card" style="width: 20rem;">
    <div class="card-body">
      <%= image_tag @name_card.image.url if @name_card.image.url  %>
    </div>
  </div>

<%= link_to '編集', edit_company_group_user_name_card_path(@company, @group, @user, @name_card), class:'btn btn-primary' %> 
<%= link_to '名刺一覧に戻る', company_group_user_name_cards_path, class:'btn btn-primary' %>