config/routes.rb
Rails.application.routes.draw do  

  devise_for :log_users
  authenticated :log_user do
    root to: 'companies#index'
  end
  root to: 'tops#index'

  resources :companies do
    resources :comments do
    end
    resources :groups do
      resources :users do
        resources :name_cards
      end
    end
  end
  
  resources :tops, only: [:index]

  post "companies/comment" => "companies#comment"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :company
 # belongs_to :user
 # belongs_to :group
 # belongs_to :name_card
end

app/models/comment_group.rb
class CommentGroup < ApplicationRecord
  belongs_to :group
end

app/models/comment_user.rb
class CommentUser < ApplicationRecord
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :groups
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
  validates :address, presence: true, length: {maximum: 100}
  validates :url, length: {maximum: 100}, format: URI.regexp(['http','https']), allow_blank: true
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}, allow_blank: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :company
  has_many :users
  has_many :comment_groups, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
end

app/models/log_user.rb
class LogUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #validates :name, presence: true, length: { maximum: 30 }

  has_many :companies
end

app/models/name_card.rb
class NameCard < ApplicationRecord
  belongs_to :user
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
 # validates :address, length: {maximum: 100}, presence: true
 # validates :url, length: {maximum: 100, allow: nil}, format: URI.regexp(['http', 'https']), allow_nil: true
 # validates :tel, :fax, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}

  mount_uploader :image, ImageUploader

end

app/models/post.rb
class Post < ApplicationRecord
  def search
    if search
      Post.where(['content LIKE ?', "%#{search}"])
    else
      Post.all
    end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :group
  has_many :name_cards
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}
  validates :mail, length: { maximum: 100, minimun: 3 }, allow_blank: true, uniqueness: true, format: { with: /\A[A-Z0-9\.\_\-_+]+@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_company
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = @company.groups.page(params[:page]).per(6)
  end

  def show
    @comments = @group.comment_groups
    @comment = @group.comment_groups.build
  end

  def new
    @group = @company.groups.new
  end

  def create
   @group = @company.groups.new(group_params)

   if @group.save
     redirect_to [@company, @group], notice: '部署を追加しました'
   else
     render action: 'new'
   end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to [@company, @group], notice: '更新しました'
    else
      render action: 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to company_groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :comment)
  end

  def set_company
      id = params[:company_id] ? params[:company_id] : params[:id]
      @company = Company.find(id)
  end

  def set_group
      group_id = params[:group_id] ? params[:group_id] : params[:id]
      @group = @company.groups.find(group_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def search
    @posts = Post.search(params[:search])
  end

  def index
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :authenticate_log_user!
    
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_company, :set_group
before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = @group.users.page(params[:page]).per(6)
  end

  def show
  end

  def new
    @user = @group.users.new
  end

  def create
    @user = @group.users.new(user_params)

    if @user.save
      redirect_to [@company, @group, @user], notice: '部署を追加しました.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to [@company, @group, @user], notice: '追加しました'
    end
  end

  def destroy
    @user.destroy
    redirect_to company_group_users_path(@company, @group)
  end

  private

  def user_params
    params.require(:user).permit(:name, :mail, :tel, :comment)
  end

  def set_company
      id = params[:company_id] ? params[:company_id] : params[:id]
      @company = Company.find(id)
  end
    
  def set_group
      group_id = params[:group_id] ? params[:group_id] : params[:id]
      @group = @company.groups.find(group_id)
  end
    
  def set_user
      user_id = params[:user_id] ? params[:user_id] : params[:id]
      @user = @group.users.find(user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/log_users_helper.rb
module LogUsersHelper

end

app/helpers/name_cards_helper.rb
module NameCardsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<div class="container">
   <div class="text-center">
       <%= form_for([@company, @group]) do |f| %>
       <% if @group.errors.any? %>
       <div id="error_exp;anation">

          <h2><%= pluralize(@group.errors.count, 'エラー') %>saved</h2>

         <ul>
           <% @group.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
         </ul>
       </div>
     <% end %>

     <div class="field">
          <%= f.text_field :name, autofocus: true, placeholder: "部署名", class: "form-control" %><br>
          <%= f.text_area :comment, autofocus: true, placeholder: "メモ", class: "form-control", rows: 12 %><br>
     </div>
       <%= f.submit "更新する", class:'btn btn-primary'%>
     
   <% end %>
   </div>
 </div>

app/views/groups/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

<%= link_to '詳細', company_group_path(@company, @group), class:'btn btn-primary' %>
<%= link_to '部署一覧へもどる', company_groups_path(@company, @group), class:'btn btn-primary' %>

app/views/groups/index.html.erb
<div class="text-primary"><h4><%= @company.name %></h4>
<h3>部署一覧</h3></div><br>

<table class="table table-hover table-striped" >
  <thead>
    <tr>
      <th>部署名</th>
      <th>メモ</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
	<td><%= "#{group.comment}".truncate(75) %></td>
        <td><%= link_to '詳細', company_group_path(@company, group), class:'btn btn-default' %>
            <%= link_to '編集', edit_company_group_path(@company, group), class:'btn btn-default' %>
            <%= link_to '削除', company_group_path(@company, group), method: :delete, data: { confirm: '削除してもいいですか?' }, class:'btn btn-default' %>
             <%= link_to '社員一覧へ', company_group_users_path(@company, group), class:'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @groups %>

<br>

<div class="text-center">
<%= link_to '部署を追加する', new_company_group_path(@company), class:'btn btn-primary' %>
<%= link_to '会社一覧へ戻る', companies_path, class:'btn btn-primary' %>
</div>

app/views/groups/new.html.erb
<div class="text-center">
  <h2>新規登録画面</h2>
</div>

<%= render 'form' %>
<%= link_to '部署一覧へ戻る', company_groups_path(@company), class:'btn btn-primary' %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-primary"><h3><%= @group.name %></h3></div>

<p>
 <div class="panel panel-title"><h4>メモ</h4></div>
  <%= @group.comment %>
</p>

<%= link_to '編集', edit_company_group_path(@company, @group), class:'btn btn-primary' %>
<%= link_to '社員一覧', company_group_users_path(@company, @group),class:'btn btn-primary' %>
<%= link_to '部署一覧へ戻る', company_groups_path(@company), class:'btn btn-primary' %>

<!--
  <div id="comments_area">
    <%#= render partial: 'comment_groups/index', locals: { comment_groups: @comments, group: @group } %>
  </div>

  <%#= render partial: 'comment_groups/form', locals: { comment_group: @comment, group: @group } %>
   -->

app/views/tops/index.html.erb
<div class="text-center">
  <div id="content">
     <h1>名刺を社内で共有するアプリ<h1>
     <h4>「あの人はよかったのに...」<h4>
     <h4> 属人的な顧客管理で行き詰まっていませんか?</h4>
     <h4>お客様との良い関係を失わないために顧客情報を見える化します<h4>
  </div>
</div>
  
<div class="container">
  <div class="col-md-12">
  <div class="text-center">
    <h2>名刺管理アプリの特徴（未完成)</h2>
  </div><br>
  
  <div class="col-md-4">
   <h4><u>顧客管理を楽にするメモ機能</u></h4>
   <p>「あの人はよかったのに...」。お客様からそう思われたら挽回するのは大変です。「あのお客様とどんな約束をしているのか。どんなルールがあるのか。」そのような各担当者しか把握していない情報をメモ機能で見える化することで、情報の属人化を防ぎスムーズな引き継ぎや営業の効率化をサポートします。</p><br>
  </div>
  
  <div class="col-md-4">
   <h4><u>名刺探しの手間を減らす検索機能</u></h4>
   <p>紙の名刺を毎回一枚一枚めくりながら探すのは面倒です。（社会人の交換した名刺の平均は1383枚。名刺を探す時間は年間20.5時間になるとの調査結果をSansan株式会社が発表しました）。 検索機能は、そんな社員の無駄な時間を減らし、他の大切な業務に取り組む時間を増やしてくれます。</p><br>
   </div>

   <div class="col-md-4">
   <h4><u>外出中にもさっと確認</u></h4>
   <p>外出中の急な面談や訪問。そんな時には名刺管理アプリをさっと開き、相手の情報を素早く確認。お客様のビジネススタイルや価値観、趣味などを確認することで、社員はお客様に適した営業をする準備ができます。</p>
  </div>
</div>
</div>

app/views/users/_form.html.erb
<div class="container">
   <div class="content-center">
     <%= form_for([@company, @group, @user]) do |f| %>
       <% if @user.errors.any? %>
       <div id="error_exp;anation">
         <h2><%= pluralize(@user.errors.count, 'エラー') %>saved</h2>
   
         <ul>
            <% @user.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
         </ul>
       </div>
     <% end %>
 
     <div class="field">
       <div class="form-low">
        <div class="col-md-5 col-xs-12">
          <%= f.text_field :name, autofocus: true, placeholder: "氏名", class: "form-control" %><br>
          <%= f.text_field :mail, autofocus: true, placeholder: "メールアドレス", class: "form-control" %><br>
          <%= f.text_field :tel, autofocus: true, placeholder: "電話番号", class: "form-control" %><br>
        </div>
        <div class="col-md-7 col-xs-12">
          <%= f.text_area :comment, autofocus: true, placeholder: "メモ", class: "form-control", rows: 12 %><br>
        </div>
       </div>
      </div>
     <div class="actions text-center "><br>
        <%= f.submit "更新する", class:'btn btn-primary' %>
    <% end %>
   </div>
</div>

app/views/users/edit.html.erb
<h1>編集する</h1>

<%= render 'form' %>
<br>

  <%= link_to '詳細', company_group_user_path(@company, @group, @user), class:'btn btn-primary' %>
  <%= link_to '社員一覧へもどる', company_group_users_path(@company, @group), class:'btn btn-primary' %>

app/views/users/index.html.erb
<div class="text-primary"><h4><%= @company.name %>:<%= @group.name %></h4>
<h3>社員一覧</h3></div>
<br>


<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>電話番号</th>
      <th>メモ</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
         <td><%= user.name %></td>
         <td><%= user.mail %></td>
         <td><%= user.tel %></td>
	 <td><%= "#{user.comment}".truncate(30) %></td>
         <td>
           <%= link_to '詳細', company_group_user_path(@company, @group, user), class:'btn btn-default'  %>
           <%= link_to '編集', edit_company_group_user_path(@company, @group, user), class:'btn btn-default' %>
           <%= link_to '削除', company_group_user_path(@company, @group, user), method: :delete, data: { confirm: '削除しますか？' }, class:'btn btn-default' %>
	   <%= link_to '名刺情報', company_group_user_name_cards_path(@company, @group, user),class:'btn btn-default' %>
         </td>
       </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

<br>
<div class="text-center">
<%= link_to '社員を追加する', new_company_group_user_path(@company, @group), class:'btn btn-primary' %>
<%= link_to '部署一覧へ戻る',company_groups_path(@company), class:'btn btn-primary' %>
</div>

app/views/users/new.html.erb
<h1>新規登録画面</h1>

<%= render 'form' %>

<%= link_to '社員一覧へ戻る', company_group_users_path(@company, @group), class:'btn btn-primary' %>

app/views/users/show.html.erb
<p id="notice" ><%= notice %></p>

<table class="table table-hover table-striped">
   <thead>
     <tr>
       <th>氏名</th>
       <th>メールアドレス</th>
       <th>電話番号</th>
       <th></th>
     </tr>
   </thead>
 
   <tbody>
       <tr>
          <td><%= @user.name %></td>
          <td><%= @user.mail %></td>
          <td><%= @user.tel %></td>
          <td>
	    <%= link_to '編集', edit_company_group_user_path(@company, @group, @user), class:'btn btn-default' %>
            <%= link_to '名刺情報', company_group_user_name_cards_path(@company, @group, @user),class:'btn btn-default' %>
	    <%= link_to '社員一覧へ戻る', company_group_users_path(@company, @group), class:'btn btn-default' %>
         </td>
         </tr>
   </tbody>
</table>
  
  <div class="panel panel-title"> <h4>メモ</h4></div>
    <%= @user.comment %>
  </div>