config/routes.rb
Rails.application.routes.draw do  

  devise_for :log_users
  authenticated :log_user do
    root to: 'companies#index'
  end
  root to: 'tops#index'

  resources :companies do
    resources :comments do
    end
    resources :groups do
      resources :users do
        resources :name_cards
      end
    end
  end
  
  resources :tops, only: [:index]

  post "companies/comment" => "companies#comment"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :company
 # belongs_to :user
 # belongs_to :group
 # belongs_to :name_card
end

app/models/comment_group.rb
class CommentGroup < ApplicationRecord
  belongs_to :group
end

app/models/comment_user.rb
class CommentUser < ApplicationRecord
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :groups
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
  validates :address, presence: true, length: {maximum: 100}
  validates :url, length: {maximum: 100}, format: URI.regexp(['http','https']), allow_blank: true
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}, allow_blank: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :company
  has_many :users
  has_many :comment_groups, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
end

app/models/log_user.rb
class LogUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #validates :name, presence: true, length: { maximum: 30 }

  has_many :companies
end

app/models/name_card.rb
class NameCard < ApplicationRecord
  belongs_to :user
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
 # validates :address, length: {maximum: 100}, presence: true
 # validates :url, length: {maximum: 100, allow: nil}, format: URI.regexp(['http', 'https']), allow_nil: true
 # validates :tel, :fax, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}

  mount_uploader :image, ImageUploader

end

app/models/post.rb
class Post < ApplicationRecord
  def search
    if search
      Post.where(['content LIKE ?', "%#{search}"])
    else
      Post.all
    end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :group
  has_many :name_cards
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}
  validates :mail, length: { maximum: 100, minimun: 3 }, allow_blank: true, uniqueness: true, format: { with: /\A[A-Z0-9\.\_\-_+]+@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, except: [:index, :new, :create]
    
  def index
    @q = Company.ransack(params[:q])
    @companies = @q.result(distinct: true).page(params[:page]).per(6)
  end

  def show
    @comments = @company.comments
    @comment = @company.comments.build
  end

  def new
    @company = Company.new
  end

  def edit
  end


  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company, notice: '会社を追加しました'
    else
      render action: 'new'
    end
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: '更新しました'
    else
      render action: 'edit'
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_url
  end


  def comment
    @company_comment = Company.find(params[:id])
    @comment = Comment.new(comment_params.merge(company_id: @company_comment.id))
    @comment.save!
      redirect_to action: :show, notice: '成功'
    rescue
      render action: :show, notice: '失敗'
  end

  def search
    @q = Company.search(search_params)
    @companies = @q.result(distinct: true)
  end


  private

  def company_params
    params.require(:company).permit(:name, :address, :tel, :fax, :url, :comment)
  end

  def comment_params
    params.require(:comment).permit(:name, :body)
  end

  def search_params
     params.require(:q).permit(:name_cont)
  end

  def set_company
     id = params[:company_id] ? params[:company_id] : params[:id]
     @company = Company.find(id)
  end

  def must_login
     if current_user.nil?
       redirect_to root_path, notice: "ログインしてください"
     end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def search
    @posts = Post.search(params[:search])
  end

  def index
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :authenticate_log_user!
    
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_company, :set_group
before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = @group.users.page(params[:page]).per(6)
  end

  def show
  end

  def new
    @user = @group.users.new
  end

  def create
    @user = @group.users.new(user_params)

    if @user.save
      redirect_to [@company, @group, @user], notice: '部署を追加しました.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to [@company, @group, @user], notice: '追加しました'
    end
  end

  def destroy
    @user.destroy
    redirect_to company_group_users_path(@company, @group)
  end

  private

  def user_params
    params.require(:user).permit(:name, :mail, :tel, :comment)
  end

  def set_company
      id = params[:company_id] ? params[:company_id] : params[:id]
      @company = Company.find(id)
  end
    
  def set_group
      group_id = params[:group_id] ? params[:group_id] : params[:id]
      @group = @company.groups.find(group_id)
  end
    
  def set_user
      user_id = params[:user_id] ? params[:user_id] : params[:id]
      @user = @group.users.find(user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/log_users_helper.rb
module LogUsersHelper

end

app/helpers/name_cards_helper.rb
module NameCardsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<div class="container">
  <div class="content-center">
    <%= form_for(@company) do |f| %>
      <% if @company.errors.any? %>
      <div id="error_exp;anation">
        <h2><%= pluralize(@company.errors.count, 'エラー') %>saved</h2>

        <ul>
          <% @company.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <div class="form-low">
       <div class="col-md-5 col-xs-12">
         <%= f.text_field :name, autofocus: true, placeholder: "会社名", class: "form-control" %><br>
         <%= f.text_field :address, autofocus: true, placeholder: "住所", class: "form-control" %><br>
         <%= f.text_field :tel, autofocus: true, placeholder: "電話番号", class: "form-control" %><br>
         <%= f.text_field :fax, autofocus: true, placeholder: "ファックス", class: "form-control" %><br>
         <%= f.text_field :url, autofocus: true, placeholder: "Webサイト", class: "form-control" %><br>
       </div>
       <div class="col-md-7 col-xs-12">
         <%= f.text_area :comment, autofocus: true, placeholder: "メモ", class: "form-control", rows: 12 %><br>
       </div>
    </div>
    </div>
    <div class="actions text-center "><br>
      <%= f.submit "更新する", class:'btn btn-primary'%>
    </div>
  <% end %>
  </div>
</div>

app/views/companies/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

<%= link_to '会社詳細', @company, class:'btn btn-primary' %>
<%= link_to '会社一覧へ戻る', companies_path, class:'btn btn-primary' %>

app/views/companies/index.html.erb
<div class="text-primary"><h3>会社一覧</h3></div>

<% provide(:name, '検索結果') %>
  <%= search_form_for @q do |f| %>
    <div class="col-xs-2"><%= f.search_field :name_cont ,class: "form-control" ,placeholder: "会社名" %></div>
    <%= f.submit '検索する', class:'btn btn-default' %>

    <% if @companies.any? %>
      <%= render 'index' %>
    <% else %>
    <p>検索結果0件でした。</p>
    <% end %>
  <% end %> <br>


<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>会社名</th>
      <th>住所</th>
      <th>電話番号</th>
      <th>ファックス</th>
      <th>Webサイト</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
   </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= company.address %></td>
      <td><%= company.tel %></td>
      <td><%= company.fax %></td>
      <td><%= link_to "#{company.url}", "#{company.url}" %></td>
      <td><%= link_to '詳細', company, class:'btn btn-default' %>
          <%= link_to '編集', edit_company_path(company), class:'btn btn-default' %>
          <%= link_to '削除', company, method: :delete, data: {confirm: '削除しますか?'} , class:'btn btn-default'%>
          <%= link_to '部署一覧へ', company_groups_path(company), class:'btn btn-default' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @companies %>

<br>
<div class="text-center">
<%= link_to '会社を新規登録する', new_company_path, class:'btn btn-primary' %>
</div>

app/views/companies/new.html.erb
<div class="text-center">
  <h2>新規登録</h2>
</div>
<%= render 'form' %>

<%= link_to '会社一覧へもどる', companies_path, class:'btn btn-primary' %>

app/views/companies/search.html.erb
<% @companies.each do |company| %>
    <%= company.name %>
<% end %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>


<table class="table table-hover">
  <thead>
    <th>会社名</th>
    <th>住所</th>
    <th>電話番号</th>
    <th>ファックス</th>
    <th>Webサイト</th>
    <th></th>
  </thead>

  <tbody>
    <tr>
    <td><%= @company.name %></td>
    <td><%= @company.address %></td>
    <td><%= @company.tel %></td>
    <td><%= @company.fax %></td>
    <td><%= @company.url %></td>
    <td>
    <%= link_to '編集', edit_company_path(@company), class:'btn btn-default' %>
    <%= link_to '部署一覧へ', company_groups_path(@company), class:'btn btn-default' %>
    <%= link_to '会社一覧へもどる', companies_path, class:'btn btn-default' %>
    </td>

    </tr>
  </tbody>
</table>

    <div>
   <div class="panel panel-title"> <h4>メモ</h4></div>
    <%= @company.comment %>
    </div>
<br>

     <div class="panel panel-title"><h4>コメント</h4></div>

  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, company: @company } %>
  </div>

  <%= render partial: 'comments/form', locals: { comment: @comment, company: @company } %>
</div>