config/routes.rb
Rails.application.routes.draw do  

  devise_for :log_users
  authenticated :log_user do
    root to: 'companies#index'
  end
  root to: 'tops#index'

  resources :companies do
    resources :comments do
    end
    resources :groups do
      resources :users do
        resources :name_cards
      end
    end
  end
  
  resources :tops, only: [:index]

  post "companies/comment" => "companies#comment"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :company
 # belongs_to :user
 # belongs_to :group
 # belongs_to :name_card
end

app/models/comment_group.rb
class CommentGroup < ApplicationRecord
  belongs_to :group
end

app/models/comment_user.rb
class CommentUser < ApplicationRecord
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :groups
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
  validates :address, presence: true, length: {maximum: 100}
  validates :url, length: {maximum: 100}, format: URI.regexp(['http','https']), allow_blank: true
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}, allow_blank: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :company
  has_many :users
  has_many :comment_groups, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
end

app/models/log_user.rb
class LogUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #validates :name, presence: true, length: { maximum: 30 }

  has_many :companies
end

app/models/name_card.rb
class NameCard < ApplicationRecord
  belongs_to :user
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
 # validates :address, length: {maximum: 100}, presence: true
 # validates :url, length: {maximum: 100, allow: nil}, format: URI.regexp(['http', 'https']), allow_nil: true
 # validates :tel, :fax, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}

  mount_uploader :image, ImageUploader

end

app/models/post.rb
class Post < ApplicationRecord
  def search
    if search
      Post.where(['content LIKE ?', "%#{search}"])
    else
      Post.all
    end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :group
  has_many :name_cards
  has_many :comments, -> { order(:created_at => :desc) },  dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}
  validates :mail, length: { maximum: 100, minimun: 3 }, allow_blank: true, uniqueness: true, format: { with: /\A[A-Z0-9\.\_\-_+]+@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :authenticate_log_user!
    
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/log_users_helper.rb
module LogUsersHelper

end

app/helpers/name_cards_helper.rb
module NameCardsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Curd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container"> 

 <nav class="navbar navbar-default">
   <ul> 
    <% if log_user_signed_in? %>
      <div class="text-right">
      <li><%= link_to "会社一覧", companies_path,class: "btn btn-primary" %>
         <%= link_to "ログアウト", destroy_log_user_session_path, method: :delete, class: "btn btn-primary"%></li><div>
    <% else %> 
      <div class="text-right">
      <li><%= link_to 'ログイン', new_log_user_session_path, class:'btn btn-primary' %>
          <%= link_to '新規登録', new_log_user_registration_path, class:'btn btn-primary' %></li></div>
    <% end %>
    </ul>
</nav>

      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p><%= flash[:alert] %></p>
      <% end %>
 
      <div class="center-block"> 
      <div id="contents">
        <%= yield %>
      </div>
      </div>

    </div>
   </div>

      <footer class="footer">
        <div class="container">
          <p class="text-muted text-center">2018 名刺管理アプリ</p>
        </div>
      </footer>

  </body>
</html>